apiVersion: v1
kind: Namespace
metadata:
  name: streaming
---
apiVersion: v1
kind: Namespace
metadata:
  name: processing
---
apiVersion: v1
kind: Namespace
metadata:
  name: lakehouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
